from pydantic import BaseModel
from datetime import datetime

from pokerdf.utils.columns import HandResult


class ValidateInput(BaseModel):
    Modality: list[str]
    TableSize: list[int]
    BuyIn: list[str]
    TournID: list[str]
    TableID: list[str]
    HandID: list[str]
    HandStartTimeCET: list[datetime]
    HandStartTimeLocal: list[datetime | None]
    HandTimezone: list[str | None]
    Level: list[str]
    Ante: list[float | None]
    Blinds: list[tuple[float, float]]
    Owner: list[str]
    OwnersHand: list[tuple[str, str]]
    Playing: list[int]
    Player: list[str]
    Seat: list[int]
    PostedAnte: list[float | None]
    Position: list[str | None]
    PostedBlind: list[float | None]
    Stack: list[float | None]
    Bounty: list[float | None]
    PreflopAction: list[list[tuple[str, str]]]
    FlopAction: list[list[tuple[str, str]]]
    TurnAction: list[list[tuple[str, str]]]
    RiverAction: list[list[tuple[str, str]]]
    AnteAllIn: list[bool]
    PreflopAllIn: list[bool]
    FlopAllIn: list[bool]
    TurnAllIn: list[bool]
    RiverAllIn: list[bool]
    BoardFlop: list[tuple[str, str, str] | tuple[()]]
    BoardTurn: list[tuple[str, str, str, str] | tuple[()]]
    BoardRiver: list[tuple[str, str, str, str, str] | tuple[()]]
    RevealedCards: list[tuple[str, str | None] | tuple[None, None]]
    CardCombination: list[str | None]
    Result: list[HandResult]
    Balance: list[float | None]
    UncalledReturned: list[float | None]
    BountyWon: list[float | None]
    TotalPotLog: list[float | None]
    Rake: list[float | None]
    PotBreakdown: list[tuple[float, ...]]
    FinalRank: list[int]
    Prize: list[float | None]
